### ISSUE TITLE
Erreur 500

### ISSUE THREAD

**Issue by GregTroar** [abarrau/Cloudlog-plugins#1]
Bonjour Aurelien,

Following the installation of the external plugin content I see the new menu below account but when I click on it I have an internal server error 500.

I have followed all steps properly and I read again, moved the files to each folder, created the database, change the config.php in both places (main and install) also chmod to www-data again the whole cloudlog folder and put proper chmod.

But I get an internal server error 500, nothing in the nginx log, not sure where to look apart from this

Thanks

**Comment by abarrau** [comment]
Hello, 
Thanks to interest to my project ;)
I will add debug information for log (still this weekend)
the external plugin forder's is create ? (cloudlog/application/third_party_pluginsext)
at this step, the code read the list of plugin folder. 
I will tell you when code will be update.
Thanks,

**Comment by GregTroar** [comment]
Yes folder created but by the way nothing inside, can it be the issue?

**Comment by GregTroar** [comment]
added the two plugins in the folder and it does not change anything so that is not the issue.

**Comment by abarrau** [comment]
Normaly with empty folder you have this :
![plugin extern empty folder](https://github.com/abarrau/Cloudlog-plugins/assets/13674762/925cc2a9-dc22-43a0-ace0-fa131c3f143e)

what is your log level, normaly a 500 Error, you must have some information in log.

**Comment by GregTroar** [comment]
Yeah I am also very surprised not to see anything in the nginx error log.
I do not know where is the log level for nginx.

Is there any log for php-fpm?? I tried using php7.4 and then 8.2 but same error

**Comment by abarrau** [comment]
In your cloudlog config.php, put the value at 4 for the log level 
line 356 => $config['log_threshold'] = 4;
And check your folder : cloudlog/application/logs
I see all error in this log files.

**Comment by GregTroar** [comment]
ok let me check

**Comment by GregTroar** [comment]
Here you go:
ERROR - 2023-11-02 13:37:41 --> Severity: error --> Exception: Unmatched '}' /var/www/html/cloudlog/application/views/pluginsext/index.php 37

**Comment by GregTroar** [comment]
So i would like to get rid of this pluginsext_allow == 1 now but for the rest there is a few bugs on the sharedata plugin:

ERROR - 2023-11-02 13:47:37 --> Severity: Warning --> Attempt to read property "onair_date" on null /var/www/html/cloudlog/application/third_party_pluginsext/sharedata/controllers/Sharedata.php 95
ERROR - 2023-11-02 13:47:37 --> Severity: error --> Exception: Attempt to assign property "onair_date" on null /var/www/html/cloudlog/application/third_party_pluginsext/sharedata/controllers/Sharedata.php 106

The on air does not work I get an internal error 500 also and above is the error.

And also the link provided for on air is wrong.

**Comment by abarrau** [comment]
I am very sorry for this problem, i will check if the code version in github is good, because i use this plugin more than 1 year without problm.

**Comment by abarrau** [comment]
> Here you go: ERROR - 2023-11-02 13:37:41 --> Severity: error --> Exception: Unmatched '}' /var/www/html/cloudlog/application/views/pluginsext/index.php 37

Normaly this '}' is necessary
![code example](https://github.com/abarrau/Cloudlog-plugins/assets/13674762/b9faecb9-3994-456e-bed4-17ae506b5297)

**Comment by GregTroar** [comment]
The problem is I have an error 500 when it is there :( where could this come from ?

**Comment by GregTroar** [comment]
Ok I will do when I have time today.
Thanks

**Comment by abarrau** [comment]
I just create a script for check installation (you can see information/example in wiki)
load this url in your browser : http://<YOUR_DOMAINE>/cloudlog/index.php/**pluginsext/check_install**

and tell me the result, thanks

**Comment by GregTroar** [comment]
Trop bien.
I am at the airport once back home I test

**Comment by GregTroar** [comment]
I have installed all the files again and here is the result:

![check_install](https://github.com/abarrau/Cloudlog-plugins/assets/24930287/88017500-bdb6-4e6d-94bf-2e12c04cc0b0)

Unfortunately I still have an error 500 with following error:

> DEBUG - 2023-11-03 10:51:33 --> [Pluginsext] Load class
ERROR - 2023-11-03 10:51:33 --> [Pluginsext] Folder found : 2, in /var/www/html/cloudlog/application/third_party_pluginsext
DEBUG - 2023-11-03 10:51:33 --> [Pluginsext] Load class
INFO - 2023-11-03 10:51:33 --> Model "Oqrs_model" initialized
INFO - 2023-11-03 10:51:33 --> Model "Logbooks_model" initialized
INFO - 2023-11-03 10:51:33 --> File loaded: /var/www/html/cloudlog/application/views/interface_assets/header.php
ERROR - 2023-11-03 10:51:33 --> Severity: error --> Exception: syntax error, unexpected '}', expecting end of file /var/www/html/cloudlog/application/views/pluginsext/index.php 37
root@Debian-Web:/var/www/html/cloudlog/application/logs#

**Comment by abarrau** [comment]
very strange situation .... 

what is your cloudlog version ? 
what is your web architecture (web server, bdd, ...) ?

Thanks,

**Comment by abarrau** [comment]
I think i am perhaps found the problem, 
reload/upload the file Cloudlog-add-files/application/views/pluginsext/index.php and tell me if ok for you , thanks

**Comment by GregTroar** [comment]
Ok doing this now.

**Comment by GregTroar** [comment]
everything is working as expected now thanks a lot !

**Comment by abarrau** [comment]
Good, so happy, ... i think, your are the first user of my plugin project !
I'm interested in any feedback --> f4ans@olindote.com
